### ISSUE TITLE
Read More button doesn't reset style

### ISSUE THREAD

**Issue by main--** [Multiverse/multiverse.github.com#1]
![Screenshot](https://dl.dropbox.com/u/21401673/mv_site_bug.png)

**Comment by fernferret** [comment]
Looks like @dumptruckman tried to fix it here https://github.com/Multiverse/multiverse.github.com/commit/c16eb9cf98f2d68df947c4b15a09cf4faca87997 I'll have a look tonight.

**Comment by fernferret** [comment]
And by tonight, I mean tonight.
